/** Catálogo dos tipos de dados nomeados no PDF Componentes fornecido. */
export const dataTypeCatalog = [
  { id: 'short-text', name: 'Texto curto', category: 'Textuais', page: 4 },
  { id: 'long-text', name: 'Texto longo', category: 'Textuais', page: 4 },
  { id: 'numeric-text', name: 'Texto numérico', category: 'Textuais', page: 4 },
  { id: 'integer', name: 'Inteiro', category: 'Numéricos', page: 4 },
  { id: 'decimal', name: 'Decimal', category: 'Numéricos', page: 4 },
  { id: 'single-select', name: 'Seleção simples', category: 'Seleções', page: 4 },
  { id: 'multi-select', name: 'Seleção múltipla', category: 'Seleções', page: 4 },
  { id: 'searchable-select', name: 'Seleção pesquisável', category: 'Seleções', page: 4 },
  { id: 'entity-select', name: 'Seleção simples de entidade', category: 'Seleções', page: 4 },
  { id: 'multi-entity-select', name: 'Seleção múltipla de entidade', category: 'Seleções', page: 4 },
  { id: 'date', name: 'Data', category: 'Especiais', page: 5 },
  { id: 'file', name: 'Arquivo', category: 'Especiais', page: 5 },
  { id: 'cpf', name: 'CPF', category: 'Específicos recorrentes', page: 5 },
  { id: 'cnpj', name: 'CNPJ', category: 'Específicos recorrentes', page: 5 },
] as const;

/** Inventário dos elementos nomeados no PDF Componentes fornecido pelo usuário. */
export const componentCatalog = [
  { id: 'geolocalizacao', name: 'Geolocalização', category: 'Cadastro', pages: '6' },
  { id: 'localizacao-simples', name: 'Localização simples', category: 'Cadastro', pages: '6–8' },
  { id: 'localizacao-com-estabelecimento', name: 'Localização com estabelecimento', category: 'Cadastro', pages: '8–10' },
  { id: 'contato', name: 'Contato', category: 'Cadastro', pages: '10' },
  { id: 'contatos-simples', name: 'Contatos simples', category: 'Cadastro', pages: '10–11' },
  { id: 'contatos-com-proprietarios', name: 'Contatos com proprietários', category: 'Cadastro', pages: '11–12' },
  { id: 'anexos-e-observacoes', name: 'Anexos e observações', category: 'Cadastro', pages: '12' },
  { id: 'proprietarios', name: 'Proprietários', category: 'Cadastro', pages: '12–13' },
  { id: 'produtores', name: 'Produtores', category: 'Cadastro', pages: '13' },
  { id: 'saldos-de-vacinas', name: 'Saldos de Vacinas', category: 'Cadastro', pages: '13–14' },
  { id: 'saldos-de-insumos', name: 'Saldos de Insumos', category: 'Cadastro', pages: '14' },
  { id: 'tabela-de-rebanho', name: 'Tabela de Rebanho', category: 'Cadastro', pages: '15' },
  { id: 'selecionar-pessoa-fisica', name: 'Selecionar pessoa física', category: 'Seleção de entidades', pages: '16' },
  { id: 'selecionar-pessoa-juridica', name: 'Selecionar pessoa jurídica', category: 'Seleção de entidades', pages: '16' },
  { id: 'selecionar-pessoa', name: 'Selecionar pessoa', category: 'Seleção de entidades', pages: '16–17' },
  { id: 'selecionar-proprietario', name: 'Selecionar proprietário', category: 'Seleção de entidades', pages: '17' },
  { id: 'selecionar-produtor', name: 'Selecionar produtor', category: 'Seleção de entidades', pages: '17' },
  { id: 'selecionar-estabelecimento-agropecuario', name: 'Selecionar estabelecimento agropecuário', category: 'Seleção de entidades', pages: '18' },
  { id: 'selecionar-exploracao-pecuaria', name: 'Selecionar exploração pecuária', category: 'Seleção de entidades', pages: '18' },
  { id: 'selecionar-nucleo-de-producao', name: 'Selecionar núcleo de produção', category: 'Seleção de entidades', pages: '18' },
  { id: 'selecionar-profissional-animal', name: 'Selecionar profissional da área animal', category: 'Seleção de entidades', pages: '19' },
  { id: 'selecionar-profissional-vegetal', name: 'Selecionar profissional da área vegetal', category: 'Seleção de entidades', pages: '19' },
  { id: 'selecionar-profissional', name: 'Selecionar profissional', category: 'Seleção de entidades', pages: '19' },
  { id: 'selecionar-profissional-servico-oficial', name: 'Selecionar profissional do serviço oficial', category: 'Seleção de entidades', pages: '20' },
  { id: 'selecionar-produto', name: 'Selecionar produto', category: 'Seleção de entidades', pages: '20' },
  { id: 'selecionar-unidade-de-medida', name: 'Selecionar unidade de medida', category: 'Seleção de entidades', pages: '20' },
  { id: 'selecionar-especie', name: 'Selecionar espécie', category: 'Seleção de entidades', pages: '20' },
  { id: 'selecionar-subespecie', name: 'Selecionar subespécie', category: 'Seleção de entidades', pages: '20–21' },
  { id: 'selecionar-cultura', name: 'Selecionar cultura', category: 'Seleção de entidades', pages: '21' },
  { id: 'selecionar-variedade-de-cultura', name: 'Selecionar variedade de cultura', category: 'Seleção de entidades', pages: '21' },
  { id: 'selecionar-doenca', name: 'Selecionar doença', category: 'Seleção de entidades', pages: '21' },
  { id: 'selecionar-tipo-de-vacina', name: 'Selecionar tipo de vacina', category: 'Seleção de entidades', pages: '21' },
  { id: 'selecionar-etapa-de-vacinacao', name: 'Selecionar etapa de vacinação', category: 'Seleção de entidades', pages: '21–22' },
  { id: 'selecionar-vacinador-brucelose', name: 'Selecionar vacinador contra brucelose', category: 'Seleção de entidades', pages: '22' },
  { id: 'selecionar-faixa-etaria', name: 'Selecionar faixa etária', category: 'Seleção de entidades', pages: '22' },
  { id: 'selecionar-saldo-de-vacinas', name: 'Selecionar saldo de vacinas', category: 'Seleção de entidades', pages: '22' },
  { id: 'selecionar-saldo-de-insumos', name: 'Selecionar saldo de insumos', category: 'Seleção de entidades', pages: '22' },
  { id: 'selecionar-revendedora', name: 'Selecionar revendedora de produtos agropecuários', category: 'Seleção de entidades', pages: '22–23' },
  { id: 'selecionar-laboratorio', name: 'Selecionar laboratório', category: 'Seleção de entidades', pages: '23' },
  { id: 'selecionar-fornecedor', name: 'Selecionar fornecedor (de vacina / insumo)', category: 'Seleção de entidades', pages: '23' },
  { id: 'selecionar-estabelecimento-agroindustrial-poa', name: 'Selecionar estabelecimento agroindustrial POA', category: 'Seleção de entidades', pages: '23–24' },
  { id: 'selecionar-evento-pecuario', name: 'Selecionar evento pecuário', category: 'Seleção de entidades', pages: '24' },
  { id: 'selecionar-unidade-administrativa', name: 'Selecionar unidade administrativa', category: 'Seleção de entidades', pages: '24' },
  { id: 'selecionar-praga', name: 'Selecionar praga', category: 'Seleção de entidades', pages: '24' },
  { id: 'selecionar-receita', name: 'Selecionar receita', category: 'Seleção de entidades', pages: '24' },
  { id: 'selecionar-item-de-receita', name: 'Selecionar item de receita', category: 'Seleção de entidades', pages: '24–25' },
  { id: 'selecionar-finalidade-de-transito', name: 'Selecionar finalidade de trânsito', category: 'Seleção de entidades', pages: '25' },
  { id: 'resultado-proprietario', name: 'Proprietário', category: 'Tabelas de resultados', pages: '26' },
  { id: 'resultado-estabelecimento-agropecuario', name: 'Estabelecimento Agropecuário', category: 'Tabelas de resultados', pages: '26' },
  { id: 'resultado-especie', name: 'Espécie', category: 'Tabelas de resultados', pages: '26' },
  { id: 'abas-relacionadas', name: 'Abas Relacionadas', category: 'Abas', pages: '27' },
  { id: 'ac001', name: 'Ações das telas de busca', category: 'Ações', pages: '28' },
  { id: 'ac002', name: 'Ações das telas de listagem', category: 'Ações', pages: '28' },
  { id: 'ac003', name: 'Ações das telas de cadastro', category: 'Ações', pages: '28–29' },
  { id: 'ac004', name: 'Ações das telas de visualização', category: 'Ações', pages: '29' },
  { id: 'ac005', name: 'Ações das telas de edição', category: 'Ações', pages: '29' },
  { id: 'ac006', name: 'Ações de interação com formulários', category: 'Ações', pages: '29–30' },
  { id: 'ac007', name: 'Ações das telas de vinculação', category: 'Ações', pages: '30' },
  { id: 'cac001', name: 'Visualizar situação do cadastro de uma entidade', category: 'Critérios de aceitação', pages: '31' },
] as const;
